# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andrei/Documents/thermo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andrei/Documents/thermo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrei/Documents/thermo/CMakeFiles /home/andrei/Documents/thermo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrei/Documents/thermo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Solver.cpp

# Build rule for target.
Solver.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Solver.cpp
.PHONY : Solver.cpp

# fast build rule for target.
Solver.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Solver.cpp.dir/build.make CMakeFiles/Solver.cpp.dir/build
.PHONY : Solver.cpp/fast

ExpressionBuilder.o: ExpressionBuilder.cpp.o
.PHONY : ExpressionBuilder.o

# target to build an object file
ExpressionBuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Solver.cpp.dir/build.make CMakeFiles/Solver.cpp.dir/ExpressionBuilder.cpp.o
.PHONY : ExpressionBuilder.cpp.o

ExpressionBuilder.i: ExpressionBuilder.cpp.i
.PHONY : ExpressionBuilder.i

# target to preprocess a source file
ExpressionBuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Solver.cpp.dir/build.make CMakeFiles/Solver.cpp.dir/ExpressionBuilder.cpp.i
.PHONY : ExpressionBuilder.cpp.i

ExpressionBuilder.s: ExpressionBuilder.cpp.s
.PHONY : ExpressionBuilder.s

# target to generate assembly for a file
ExpressionBuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Solver.cpp.dir/build.make CMakeFiles/Solver.cpp.dir/ExpressionBuilder.cpp.s
.PHONY : ExpressionBuilder.cpp.s

FlashCalculation.o: FlashCalculation.cpp.o
.PHONY : FlashCalculation.o

# target to build an object file
FlashCalculation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Solver.cpp.dir/build.make CMakeFiles/Solver.cpp.dir/FlashCalculation.cpp.o
.PHONY : FlashCalculation.cpp.o

FlashCalculation.i: FlashCalculation.cpp.i
.PHONY : FlashCalculation.i

# target to preprocess a source file
FlashCalculation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Solver.cpp.dir/build.make CMakeFiles/Solver.cpp.dir/FlashCalculation.cpp.i
.PHONY : FlashCalculation.cpp.i

FlashCalculation.s: FlashCalculation.cpp.s
.PHONY : FlashCalculation.s

# target to generate assembly for a file
FlashCalculation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Solver.cpp.dir/build.make CMakeFiles/Solver.cpp.dir/FlashCalculation.cpp.s
.PHONY : FlashCalculation.cpp.s

MatrixOperations.o: MatrixOperations.cpp.o
.PHONY : MatrixOperations.o

# target to build an object file
MatrixOperations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Solver.cpp.dir/build.make CMakeFiles/Solver.cpp.dir/MatrixOperations.cpp.o
.PHONY : MatrixOperations.cpp.o

MatrixOperations.i: MatrixOperations.cpp.i
.PHONY : MatrixOperations.i

# target to preprocess a source file
MatrixOperations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Solver.cpp.dir/build.make CMakeFiles/Solver.cpp.dir/MatrixOperations.cpp.i
.PHONY : MatrixOperations.cpp.i

MatrixOperations.s: MatrixOperations.cpp.s
.PHONY : MatrixOperations.s

# target to generate assembly for a file
MatrixOperations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Solver.cpp.dir/build.make CMakeFiles/Solver.cpp.dir/MatrixOperations.cpp.s
.PHONY : MatrixOperations.cpp.s

PropertyPackage.o: PropertyPackage.cpp.o
.PHONY : PropertyPackage.o

# target to build an object file
PropertyPackage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Solver.cpp.dir/build.make CMakeFiles/Solver.cpp.dir/PropertyPackage.cpp.o
.PHONY : PropertyPackage.cpp.o

PropertyPackage.i: PropertyPackage.cpp.i
.PHONY : PropertyPackage.i

# target to preprocess a source file
PropertyPackage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Solver.cpp.dir/build.make CMakeFiles/Solver.cpp.dir/PropertyPackage.cpp.i
.PHONY : PropertyPackage.cpp.i

PropertyPackage.s: PropertyPackage.cpp.s
.PHONY : PropertyPackage.s

# target to generate assembly for a file
PropertyPackage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Solver.cpp.dir/build.make CMakeFiles/Solver.cpp.dir/PropertyPackage.cpp.s
.PHONY : PropertyPackage.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Solver.cpp.dir/build.make CMakeFiles/Solver.cpp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Solver.cpp.dir/build.make CMakeFiles/Solver.cpp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Solver.cpp.dir/build.make CMakeFiles/Solver.cpp.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Solver.cpp"
	@echo "... ExpressionBuilder.o"
	@echo "... ExpressionBuilder.i"
	@echo "... ExpressionBuilder.s"
	@echo "... FlashCalculation.o"
	@echo "... FlashCalculation.i"
	@echo "... FlashCalculation.s"
	@echo "... MatrixOperations.o"
	@echo "... MatrixOperations.i"
	@echo "... MatrixOperations.s"
	@echo "... PropertyPackage.o"
	@echo "... PropertyPackage.i"
	@echo "... PropertyPackage.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

